<a href="https://colab.research.google.com/github/tejsvinimeshram/Practical-no.-3/blob/main/EE524_task3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import pandas as pd

file = "wireless_signal_quality_dataset.csv"

with open(file, 'r') as f:
    lines = f.readlines()

# Assuming the first line is the header
# Strip leading/trailing whitespace and then strip any surrounding double quotes
header = [h.strip().strip('"') for h in lines[0].strip().split(',')]

# Assuming the rest are data rows
data_rows = []
for line in lines[1:]:
    # Split each line by comma and then strip whitespace and quotes from each element
    cleaned_row = [item.strip().strip('"') for item in line.strip().split(',')]
    data_rows.append(cleaned_row)

data = pd.DataFrame(data_rows, columns=header)

In [ ]:

print(data.head())

  Signal_Strength_dBm SNR_dB Interference_dB Distance_m Frequency_GHz  \
0                 -41      6               0        257             5   
1                 -86     25              20        134           2.4   
2                 -73     27               0        385           2.4   
3                 -57      5               0        255             5   
4                 -87     15              24         61             5   

  Channel_Bandwidth_MHz Noise_Floor_dBm Connected_Devices  \
0                   160            -100                24   
1                   160             -96                41   
2                    20             -72                13   
3                   160             -86                 9   
4                    20             -79                32   

  Estimated_Throughput_Mbps Quality  
0                        18    Poor  
1                        55    Poor  
2                        81    Fair  
3                        15    Poor  
4   

In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
data['quality'] = label_encoder.fit_transform(data['Quality'])

In [ ]:
X=data.drop('quality',axis=1)
y=data['quality']

In [ ]:
x=pd.get_dummies(X,drop_first=True)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import(accuracy_score, classification_report, confusion_matrix)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler

#Feature Scaling
#---------------------------
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
#--------------------------
#Train Logistic Regression Model
#--------------------------
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)


LogisticRegression(max_iter=1000)

In [ ]:
#Prediction
y_pred = model.predict(X_test)

In [ ]:
#Evalution
print("\nAccuracy:")
print(accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))



Accuracy:
0.8

Confusion Matrix:
[[0 0 0 1]
 [0 6 0 0]
 [0 1 1 1]
 [0 1 0 9]]

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.75      1.00      0.86         6
           2       1.00      0.33      0.50         3
           3       0.82      0.90      0.86        10

    accuracy                           0.80        20
   macro avg       0.64      0.56      0.55        20
weighted avg       0.78      0.80      0.76        20



/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
